name: Firebase
on:
  push:
    branches:
      - develop
jobs:
  develop:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./functions
        run: npm install
      - name: Build
        working-directory: ./functions
        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          TARGET: default
